name: .NET

on:
  pull_request:
    branches: 
    - main

defaults:
  run:
    working-directory: ./src

jobs:
  build:

    runs-on: ubuntu-latest
    env: 
      working-directory: ./src
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: AWS CLI install
      run: dotnet tool install -g Amazon.Lambda.Tools
    - name: AWS CLI update
      run: dotnet tool update -g Amazon.Lambda.Tools
    - name: Restore dependencies
      run: dotnet restore LambdaAuth.sln
    - name: Build
      run: dotnet build --no-restore LambdaAuth.sln
    - name: Deploy to Lambda
      working-directory: ./src/LambdaAuth
      run: dotnet lambda deploy-serverless
